name: space_agent
services:
  space-agent:
    cpu_shares: 90
    command: []
    container_name: space-agent
    deploy:
      resources:
        limits:
          memory: 8063M
    environment:
      - CUSTOMWARE_PATH=/app/customware
      - GIT_BACKEND=auto
      - HOST=0.0.0.0
      - SPACE_AUTH_DATA_DIR=/app/server/data
    hostname: space-agent
    image: gabrielcmoris/agent-sp-space:latest
    labels:
      icon: https://space-agent.ai/pages/res/astronaut_no_bg.webp
    ports:
      - target: 3000
        published: "4444"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/spaceAgent/customware
        target: /app/customware
      - type: bind
        source: /DATA/AppData/spaceAgent/server
        target: /app/server/data
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://space-agent.ai/pages/res/astronaut_no_bg.webp
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: glorious_ubs
  title:
    custom: ""
    en_us: space-agent
volumes:
  space_agent_data: