name: hermes-agent
services:
  hermes-agent:
    cpu_shares: 90
    command:
      - gateway
      - run
    container_name: agent-hermes
    deploy:
      resources:
        limits:
          memory: 8063M
    environment:
      - API_SERVER_CORS_ORIGIN=*
      - API_SERVER_ENABLED=true
      - API_SERVER_HOST=0.0.0.0
      - API_SERVER_KEY=sk_hermes_32_CHAR_TOKEN
      - API_SERVER_PORT=8642
      - HERMES_HOME=/root/.hermes
      - MESSAGING_CWD=/root/.hermes/workspace
      - TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_TOKEN
    hostname: agent-hermes
    image: nousresearch/hermes-agent:latest
    labels:
      icon: https://hermes-agent.nousresearch.com/docs/img/logo.png
    ports:
      - target: 8642
        published: "8642"
        protocol: tcp
      - target: 3000
        published: "3000"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    shm_size: "3221225472"
    user: 0:0
    volumes:
      - type: bind
        source: /DATA/AppData/agentHermes
        target: /root/.hermes
    devices: []
    cap_add: []
    networks:
      - ollama
networks:
  ollama:
    name: ollama
    external: true
x-casaos:
  author: gabrielcmoris
  category: AI_AGENTS
  hostname: hermes.gabrielcmoris.com
  icon: https://hermes-agent.nousresearch.com/docs/img/logo.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: hermes-agent
  tips:
    custom: |-
      ❗❗❗IMPORTANT❗❗❗
      After container starts you must run:
      1. hermes setup
      2. git clone https://github.com/outsourc-e/hermes-workspace.git
      3. cd hermes-workspace
      4. pnpm install
      5. pnpm dev
  title:
    custom: hermes-agent
    en_us: hermes-agent
