name: flourishing_et
services:
  hermes-agent:
    cpu_shares: 90
    command:
      - gateway
      - run
    container_name: agent-hermes
    deploy:
      resources:
        limits:
          memory: 8063M
    environment:
      - API_SERVER_ENABLED=true
      - API_SERVER_HOST=0.0.0.0
      - API_SERVER_KEY=sk_hermes_GENERATE_AN_API_KEY
      - API_SERVER_PORT=8642
      - HERMES_HOME=/root/.hermes
      - MESSAGING_CWD=/root/.hermes/workspace
      - TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_TOKEN
    hostname: agent-hermes
    image: nousresearch/hermes-agent:latest
    labels:
      icon: https://hermes-agent.nousresearch.com/docs/img/logo.png
    ports:
      - target: 8642
        published: "8642"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    shm_size: "3221225472"
    user: 0:0
    volumes:
      - type: bind
        source: /DATA/AppData/agentHermes
        target: /root/.hermes
    devices: []
    cap_add: []
    networks:
      - ollama
  hermes-webui:
    cpu_shares: 90
    command: []
    container_name: webui-hermes
    depends_on:
      hermes-agent:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 8063M
    environment:
      - HERMES_WEBUI_HOST=0.0.0.0
      - HERMES_WEBUI_PASSWORD=YOUR_PASSWORD_FOR_WEBUI
      - HERMES_WEBUI_PORT=8787
      - HERMES_WEBUI_STATE_DIR=/webui-state
      - OPENAI_API_BASE_URL=http://hermes-agent:8642/v1
      - OPENAI_API_KEY=sk_hermes_GENERATE_AN_API_KEY
    hostname: webui-hermes
    image: ghcr.io/nesquena/hermes-webui:latest
    labels:
      icon: https://hermes-agent.nousresearch.com/docs/img/logo.png
    ports:
      - target: 8787
        published: "8787"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/agentHermes
        target: /root/.hermes
    devices: []
    cap_add: []
    networks:
      - ollama
networks:
  ollama:
    name: ollama
x-casaos:
  author: self
  category: self
  hostname: hermes.gabrielcmoris.com
  icon: https://hermes-agent.nousresearch.com/docs/img/logo.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: flourishing_et
  title:
    custom: hermes-agent
    en_us: hermes-agent
